#!/bin/bash
# fast method to add changes to this repo
COMMENT="new changes"
if [[ "$@" != "" ]]; then
    COMMENT="$@"
fi
TAG_NAME=v1.0.0
git add --all
git commit -m "$COMMENT"
git push
git tag -f -a ${TAG_NAME} -m "version ${TAG_NAME}"
git push -f origin ${TAG_NAME}