#!/bin/bash
# fast method to add changes to this repo
TAG_NAME=v1.13.0
COMMENT="Added class to manipulate with price \bfday\PHPDailyFunctions\Helpers\Price"
if [[ "$@" != "" ]]; then
    COMMENT="$@"
fi
while true; do	
	read -p "commit description: '$COMMENT'. tag name: '$TAG_NAME'. commit? (y,n) " yn
	case $yn in
		[Yy]* ) break;;
		[Nn]* ) echo 'Canceled.'; exit 1;;
		* ) echo "Please answer yes or no.";;
	esac
done
git add --all
git commit -m "$COMMENT"
git push
git tag -f -a ${TAG_NAME} -m "version ${TAG_NAME}"
git push -f origin ${TAG_NAME}
